from train import *

print("\n 1 – MNIST ")
print("1.1 – CNN ")
"""run_snntorch("MnistCnnMseB04",
             num_train=500,
             num_test=100,
             batch_size=8,
             kernel=4,
             section=2000,
             beta=0.2,
             model="CNN",
             loss="mse",
             set="mnist"
             )
run_snntorch("MnistCnnCeB04",
             num_train=500,
             num_test=100,
             batch_size=8,
             kernel=4,
             section=2000,
             beta=0.2,
             model="CNN",
             loss="ce",
             set="mnist"
             )
print("\n \n 1.2 – RNN Two ")
run_snntorch("Mnist2RnnMseB04",
             num_train=500,
             num_test=100,
             batch_size=8,
             section=2000,
             beta=0.2,
             model="2RNN",
             loss="mse",
             set="mnist"
             )"""
run_snntorch("Mnist2RnnCeB04",
             num_train=500,
             num_test=100,
             batch_size=8,
             kernel=4,
             section=2000,
             beta=0.2,
             model="2RNN",
             loss="ce",
             set="mnist"
             )
print("\n \n 1.3 – RNN One ")
run_snntorch("Mnist1RnnMseB04",
             num_train=500,
             num_test=100,
             batch_size=8,
             section=2000,
             beta=0.2,
             model="SimpRNN",
             loss="mse",
             set="mnist"
             )
run_snntorch("Mnist1RnnCeB04",
             num_train=500,
             num_test=100,
             batch_size=8,
             kernel=4,
             section=2000,
             beta=0.2,
             model="SimpRNN",
             loss="ce",
             set="mnist"
             )

"""


run_snntorch("10Dvs2RnnMseB04_0",
             num_train=120,
             num_test=15,
             batch_size=8,
             section=2000,
             beta=0.4,
             model="2RNN",
             loss="mse",
             set="dvs"
             )
run_snntorch("10Dvs2RnnMseB04_1",
             num_train=120,
             num_test=15,
             batch_size=8,
             section=2000,
             beta=0.4,
             model="2RNN",
             loss="mse",
             set="dvs"
             )
run_snntorch("10Dvs2RnnMseB04_2",
             num_train=120,
             num_test=15,
             batch_size=8,
             section=2000,
             beta=0.4,
             model="2RNN",
             loss="mse",
             set="dvs"
             )
run_snntorch("10Dvs2RnnMseB04_3",
             num_train=120,
             num_test=15,
             batch_size=8,
             section=2000,
             beta=0.4,
             model="2RNN",
             loss="mse",
             set="dvs"
             )
"""
